spring.application.name=car

spring.datasource.url=jdbc:mysql://localhost:3306/car_db
spring.datasource.username=root
spring.datasource.password=HaNnAh22_18@

# JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
